### ISSUE TITLE
Ошибка при некорректном времени напоминания

### ISSUE THREAD

**Issue by AnastasiaMarkeeva** [AnastasiaMarkeeva/test_calendar.mail.ru#3]
**Как воспроизвести**
Внести время напоминания: за 9999 дней по почте, когда до события осталось меньше 9999 дней.
**Фактический результат**
После сохранения ошибка при соединении с сервером, исчезновение события. (Для сравнения, при корректном количестве дней ошибка не выходит.)
**Ожидаемый результат**
Предупреждение об ошибке до сохранения с возможностью исправить.

![calend3](https://cloud.githubusercontent.com/assets/15799027/11092782/e86e71a4-8896-11e5-80fa-907f96f380de.png)
![calend4](https://cloud.githubusercontent.com/assets/15799027/11092781/e838257c-8896-11e5-85ec-d3c4aa229571.png)

**Comment by JuliaYar** [comment]
Ошибка возникает только при вводе 9999? Корректный ввод - это время напоминания меньше времени до события? Расшифруйте, пожалуйста, "при корректном количестве дней".

**Comment by AnastasiaMarkeeva** [comment]
Да, при корректном количестве дней - это время напоминания меньше времени до события. С момента нахождения ошибки она успела измениться, кстати. Теперь при том же вводе нет серверной ошибки, просто сохраняется уведомление по умолчанию за 15 минут по почте.

**Comment by JuliaYar** [comment]
Спасибо
